---

- name: update system
  hosts: all
  sudo: yes
  tasks:
    - include: tasks/apt-update.yml

- name: install system dependencies
  hosts: all
  roles:
    - role: apt_get_install
      # Required packages
      # * acl is required for the ansible acl module.
      # * essentially everything that gets built requires build-essential.
      items:
        - acl
        - build-essential

- name: install hubot
  hosts: all
  sudo: yes
  gather_facts: yes
  roles:
    - role: brianshumate.hubot
      hubot_adapter: xmpp
      hubot_ower: "OpenStax"
      hubot_node_packages:
        - cheerio
        - clark
        - cleverbot-node
        - htmlparser
        - hubot-calculator
        - hubot-hipchat-emoticons
        - nodepie
        - soupselect
        - hubot-youtube
        - lodash
        - moment
        - chrono-node
      hubot_custom_scripts:
        - achievement_unlocked.coffee
        - ackbar.coffee
        - applause.coffee
        - ascii.coffee
        - base64.coffee
        - bees.coffee
        - botsnack.coffee
        - cat.coffee
        - cleverbot.coffee
        - coin.coffee
        - dealwithit.coffee
        - decide.coffee
        - fortune.coffee
        - github-status.coffee
        - grumpycat.coffee
        - hackernews.coffee
        - megusta.coffee
        - ping.coffee
        - redis-brain
        - reddit
        - reddit-jokes.coffee
        - reddit-random-top.coffee
        - remind.coffee
        - stallman.coffee
        - twss
        - wunderground.coffee
        - xkcd.coffee
        - zombies.coffee
